name: Deploy to cloudtype
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: marshot9420/marsmall
          stage: main
          yaml: |
            name: marsmall-backend
            app: node@20
            options:
              env:
                - name: NODE_ENV
                  var: NODE_ENV
                - name: HOST
                  secret: HOST
                - name: PORT
                  secret: PORT
                - name: CLIENT_PORT
                  secret: CLIENT_PORT
                - name: ADMIN_USER
                  secret: ADMIN_USER
                - name: ADMIN_PASSWORD
                  secret: ADMIN_PASSWORD
                - name: DB_HOST
                  secret: DB_HOST
                - name: DB_PORT
                  secret: DB_PORT
                - name: DB_NAME
                  secret: DB_NAME
                - name: DB_USER
                  secret: DB_USER
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
              ports: "4000"
              build: yarn build
              start: yarn start:prod
              install: yarn
              healthz: /healthz
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: nest.js
